title: Jekyll Webpack Starter Kit
description: >
  Hopefully, an enjoyable, modern,
  static site generator starter kit.

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

exclude:
  - _assets
  - vendor
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
