version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    command: yarn start
    container_name: jekyll.node
    environment:
      - DOCKER=true
    ports:
      - 3000:3000
      - 3001:3001
      - 4000:4000
    volumes:
      - .:/code

  ruby:
    build:
      context: .
      dockerfile: ./.docker/ruby/Dockerfile
    command: bundle exec jekyll build --watch
    container_name: jekyll.ruby
    environment:
      - DOCKER=true
    volumes:
      - .:/code
